run:
  build-tags:
    - integration
linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - gocritic
linters-settings:
  gosec:
    excludes:
      # performance bug in gosec. See https://github.com/golangci/golangci-lint/issues/4039
      # and https://github.com/securego/gosec/issues/1007
      - G602
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam
      - sloppyTestFuncName
      - unnamedResult
issues:
  exclude-rules:
    - linters:
        - dupl
        - unparam
        - gosec
        - dogsled
      path: _test\.go

    # We need to pass nil Context in order to test DoBare erroring on nil ctx.
    - linters: [ staticcheck ]
      text: 'SA1012: do not pass a nil Context'
      path: _test\.go

    # We need to use sha1 for validating signatures
    - linters: [ gosec ]
      text: 'G505: Blocklisted import crypto/sha1: weak cryptographic primitive'
