concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push: {}

name: tests
env:
  GO111MODULE: on

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: WillAbides/setup-go-faster@v1
      id: setup-go
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v4

    - uses: actions/cache@v3
      with:
        path: |
          ${{ steps.setup-go.outputs.GOCACHE }}
          ${{ steps.setup-go.outputs.GOMODCACHE }}
        key: ${{ runner.os }}-go-debug-

    - name: build metadata
      run: go -C tools build -o "/tmp/metadata" ./cmd/metadata

#    - name: Ensure go generate produces a zero diff
#      shell: bash
#      run: go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
