on:
  push: {}
jobs:
  tinker:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: WillAbides/setup-go-faster@v1
        id: setup-go
        with:
          go-version: '1.20.x'
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-go.outputs.GOCACHE }}
            ${{ steps.setup-go.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-tinker2-${{ hashFiles('./tools/go.mod') }}
          restore-keys: ${{ runner.os }}-tinker2-
      - run: go mod download
        working-directory: ./tools
      - run: go test . -run TestHelp -v
        working-directory: ./tools/metadata
